[build]
  command = "npm run build"
  publish = "dist"
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/studio/*"
  to = "/studio/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200 
  force = true

